version: 2.19.03
jobs:
   build:
     docker:
       - image: circleci/node:12.18.0
     steps:
       - checkout
       - run: npm install
       - run: npm run build
   test:
     docker:
       - image: circleci/node:12.18.0
     steps:
       - checkout
       - run: npm install
       - run: npm run test
workflows:
  version: 2.19.03
  test-build:
    jobs:
      - test
      - build:
          requires:
            - test