export const CHANGE_SEARCH_FIELD_STATE='CHANGE_SEARCH_FIELD_STATE';
export const CHANGE_SEARCH_FIELD_DESTINATION='CHANGE_SEARCH_FIELD_DESTINATION';

export const REQUEST_PLACELIST_PENDING='REQUEST_PLACELIST_PENDING';
export const REQUEST_PLACELIST_SUCCESS='REQUEST_PLACELIST_SUCCESS';
export const REQUEST_PLACELIST_FAILED='REQUEST_PLACELIST_FAILED';